[project]

name = "e-neiler"
version = "0.1.0"
description = "Fully customizable SMTP e-mailer script."
dependencies = [
    "pyside6==6.7.3",
    "pyside6-fluent-widgets==1.6.6",
    "pandas===2.2.2",
    "html2text==2024.2.26",
]

[project.optional-dependencies]

compiler = ["nuitka==2.4.8"]
