name: deploy

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: deploy
  cancel-in-progress: true

env:
  NAME: E-neiler
  AUTHOR: NEIAAC
  SIGNATURE: com.neiaac.e-neiler

defaults:
  run:
    shell: bash

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract.outputs.version }}
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2
      - name: Extract version from pyproject.toml
        id: extract
        run: |
          VERSION=$(awk -F\" '/^version =/ { print $2 }' pyproject.toml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  macos:
    needs: [prepare]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install .[build]

      - name: Build artifact
        uses: Nuitka/Nuitka-Action@8462c393e3dfa2bea614d9f448f989c88ad9f9e4 # v1.3.0
        with:
          nuitka-version: 2.7
          script-name: src/main.py
          mode: app
          include-data-dir: src/resources=resources
          macos-app-icon: src/resources/icons/logo.png
          macos-signed-app-name: ${{ env.SIGNATURE }}
          macos-app-name: ${{ env.NAME }}
          macos-app-version: ${{ needs.prepare.outputs.version }}
          product-version: ${{ needs.prepare.outputs.version }}
          file-version: ${{ needs.prepare.outputs.version }}
          company-name: ${{ env.AUTHOR }}
          product-name: ${{ env.NAME }}
          file-description: ${{ env.NAME }} app, created by ${{ env.AUTHOR }}.
          output-dir: build
          enable-plugins: pyside6

      - name: Zip build
        working-directory: build
        run: zip -r Linux.zip .
      - name: Append build to release
        working-directory: build
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release upload --clobber v${{ needs.prepare.outputs.version }} Linux.zip

  linux:
    needs: [prepare]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install .[build]

      - name: Build artifact
        uses: Nuitka/Nuitka-Action@8462c393e3dfa2bea614d9f448f989c88ad9f9e4 # v1.3.0
        with:
          nuitka-version: 2.7
          script-name: src/main.py
          mode: app
          include-data-dir: src/resources=resources
          linux-icon: src/resources/icons/logo.png
          product-version: ${{ needs.prepare.outputs.version }}
          file-version: ${{ needs.prepare.outputs.version }}
          company-name: ${{ env.AUTHOR }}
          product-name: ${{ env.NAME }}
          file-description: ${{ env.NAME }} app, created by ${{ env.AUTHOR }}.
          output-dir: build
          enable-plugins: pyside6
          clang: true
          static-libpython: yes

      - name: Zip build
        working-directory: build
        run: zip -r MacOS.zip .
      - name: Append build to release
        working-directory: build
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release upload --clobber v${{ needs.prepare.outputs.version }} MacOS.zip

  windows:
    needs: [prepare]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install .[build]

      - name: Build binaries
        uses: Nuitka/Nuitka-Action@8462c393e3dfa2bea614d9f448f989c88ad9f9e4 # v1.3.0
        with:
          nuitka-version: 2.7
          script-name: src/main.py
          mode: app
          include-data-dir: src/resources=resources
          windows-icon-from-ico: src/resources/icons/logo.png
          windows-console-mode: disable
          product-version: ${{ needs.prepare.outputs.version }}
          file-version: ${{ needs.prepare.outputs.version }}
          company-name: ${{ env.AUTHOR }}
          product-name: ${{ env.NAME }}
          file-description: ${{ env.NAME }} app, created by ${{ env.AUTHOR }}.
          output-dir: build
          enable-plugins: pyside6

      - name: Zip build
        working-directory: build
        run: zip -r Windows.zip .
      - name: Append build to release
        working-directory: build
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release upload --clobber v${{ needs.prepare.outputs.version }} Windows.zip
