name: release

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      desktop: ${{ steps.metadata.outputs.release_created }}
    steps:
      - name: Update project metadata and the release pull request
        uses: googleapis/release-please-action@1155c2c8dcbd6b15e85bae6bc6d1fed9552663cb # v4.2.0
        id: metadata
        with:
          release-type: python

  desktop:
    needs: [metadata]
    if: ${{ needs.metadata.outputs.desktop }}
    uses: ./.github/workflows/deploy.yaml
